theme: jekyll-theme-minimal
# title: Mapper Interactive
description: Mapper Interactive is a highly customizable visualization framework for you to visualize and explore Mapper algorithm.
logo: ./28923103_padded_logo.png
show_downloads: false